### ISSUE TITLE
[BUG] Ошибка загрузки данных

### ISSUE THREAD

**Issue by evskorobogatij** [liquetsoft/fias-symfony#22]
При выполнении ` bin/console liquetsoft:fias:install`

Получаю ошибку:
`
Error while running Liquetsoft\Fias\Component\Pipeline\Task\InformFullTask task: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://fias.nalog.ru/
  WebServices/Public/DownloadService.asmx?WSDL' : failed to load external entity "http://fias.nalog.ru/WebServices/Public/DownloadService.asmx?WSDL"
`

`SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://fias.nalog.ru/WebServices/Public/DownloadService.asmx?WSDL' : failed to load external entity "h
  ttp://fias.nalog.ru/WebServices/Public/DownloadService.asmx?WSDL"
`

**Comment by marvin255** [comment]
У меня файл доступен. Перепроверьте, пожалуйста, еще раз. Возможно была разовая проблема на ФИАС. Возможно проблема в коннекте между ФИАСом и целевым сервером. Я проверю наши площадки.

**Comment by marvin255** [comment]
Проблему не наблюдаю в данный момент.
