### ISSUE TITLE
symfony 3

### ISSUE THREAD

**Issue by makm** [liquetsoft/fias-symfony#4]
Можно ли включить поддержку sf3 в компосере ?

**Comment by makm** [comment]
прошу прощения. все отлично работает в sf4.  Нао

**Comment by marvin255** [comment]
Не думаю, что смогу сделать поддержку для sf3. Очент много всего использовал из новых библиотек. Могу посоветовать сделать отдельный проект только для загрузки данных ФИАС, а в основном проекте на sf3 просто использовать ту же таблицу, что наполянется в ФИАС проекте.

Честно признаюсь что писать бандл для sf3 нет ни времени, ни навыков.

**Comment by makm** [comment]
Спасибо за ответ.  На самом деле, пока проект тестовый - просто перешел на sf4 
Но столкнулся уже с еще 2мя проблемами
1) rar расширение под 7.3 не компилируется, на скорую руку сделал такое решение 
https://github.com/makm/makm-fias-bundle-rar-unpacker/blob/master/src/RarArchiverUnpacker.php

2) если хост fias.nalog.ru лежит, то при вызове bin/console вылетают исключения
`In getLiquetsoftFias_Informer_ServiceService.php line 9:
                                                                                                                                                               
  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://fias.nalog.ru/WebServices/Public/DownloadService.asmx?WSDL' : failed to load external entity "http://f  
  ias.nalog.ru/WebServices/Public/DownloadService.asmx?WSDL"                                                                                                   
                                                               `

**Comment by marvin255** [comment]
1. В ближайшее время выкачу фикс для этого, уже есть в основной библиотеке, в бандле еще нет.
2. Я на такое поведение и рассчитывал, то есть если мы не можем найти ссылку для обновления, то дальше просто не идем. Какое поведение на ваш взгляд было бы более оправданным?

**Comment by marvin255** [comment]
Добавлено в v3.2.0.
