### ISSUE TITLE
Некорректная конвертация кодов КЛАДР

### ISSUE THREAD

**Issue by simolex** [liquetsoft/fias-symfony#70]
Некорректная десериализация  значений кодов КЛАДР длиной более 18 символов

Проблема выявлена в сущности Param в поле value.
При конвертации, например, значения "227010000010000016740025000000000" оно сохраняется в таблице в виде "2.2701000001E+32" (экспоненциальной записи)

**Comment by liquetsoft** [comment]
Исправлено в https://github.com/liquetsoft/fias-symfony/pull/71
Должно работать как с `FiasSerializer`, так и сериализатором, который предоставляет сам фрэймворк.
